### ISSUE TITLE
Implement email verfication

### ISSUE THREAD

**Issue by govind-kumarr** [govind-kumarr/simple_rag_dashboard#11]
Currently, users can enter an invalid email while signing up and can use our services which is not ideal. Write backend APIs to verify their emails Send verification emails to their email address. Limit the memory usage to 10% unless user verifies their emails.

**Comment by Latish705** [comment]
@govind-kumarr I would like to work on this assign it to me

**Comment by govind-kumarr** [comment]
@Latish705 Go ahead! Create a PR asap.

**Comment by govind-kumarr** [comment]
You can bypass it and pass there any random value as this task does not require an open ai thing.

**Comment by Latish705** [comment]
@govind-kumarr I am done with email verification can tell me more in detail what to do 10% memory usage

**Comment by govind-kumarr** [comment]
@Latish705  Can you create a PR for it? Once I review it I will create other issues related to this.

**Comment by Latish705** [comment]
@govind-kumarr created pull request ready for review

**Comment by Latish705** [comment]
@govind-kumarr Would love to work on its frontend part
