### ISSUE TITLE
Implement email verfication

### ISSUE THREAD

**Issue by govind-kumarr** [govind-kumarr/simple_rag_dashboard#12]
Once APIs get ready for email verification. Modify the frontend according to that. Email verification page is already there but there is a lot to do. e.g. alerting user to verify their email when they login. showing memory limit.
![Screenshot (629)](https://github.com/govind-kumarr/simple_rag_dashboard/assets/106414173/927bfd1d-9726-4149-878d-b3579268c950)

**Comment by ayan-joshi** [comment]
I can work on this issue , frontend we can get it ready so can easily integrate when apis are ready

**Comment by tusharyadav11** [comment]
Hello Sir,
I can add this which will enhance the beauty of your website.
Please assign this issue to me under GSSOC 2024
@govind-kumarr

**Comment by Latish705** [comment]
@govind-kumarr I would like to work on this I have also developed backend api for verification

**Comment by ratiruhela9** [comment]
@govind-kumarr i would like to work on this issue. please assign this to me

**Comment by sleathblack007** [comment]
Hello Sir,
I can add this which will enhance the beauty of your website.
Please assign this issue to me under GSSOC 2024
@govind-kumarr

**Comment by Satwik-Kar** [comment]
This issue caught my eye, and I'm curious to dig in. Let's team up and crack this one together! Excited to work on it with you!
@govind-kumarr . Kindly assign me this issue under **GSSOC'24**.

**Comment by Shravani246** [comment]
@gk12 I can work on this issue.Assign it!

**Comment by sakshamgumber** [comment]
i can do it please assign it to me sir @gk12  i can implment this with the api

**Comment by piyush-gangrade** [comment]
@gk12 I would like to work on this issue, please assign me this under GSSoC'24
