### ISSUE TITLE
There is cors error from frontend to backend 

### ISSUE THREAD

**Issue by Latish705** [govind-kumarr/simple_rag_dashboard#13]
# There is cors error from frontend to backend 

<img width="1427" alt="image" src="https://github.com/govind-kumarr/simple_rag_dashboard/assets/104522651/57de4481-53a0-459e-b42c-10d394b9bc77">

I would like to work on this please assign to me this as well

**Comment by Latish705** [comment]
@govind-kumarr I would like to work on this as well

**Comment by govind-kumarr** [comment]
@Latish705  Can you check it locally? it is working fine. Please ignore the deployment for now this is probably issue with env variables and netlify I will resolve it later.
