### ISSUE TITLE
Missing Code of Conduct File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [govind-kumarr/simple_rag_dashboard#14]
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behaviour, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Please assign this issue to me.

**Comment by govind-kumarr** [comment]
@suhanipaliwal  Hi buddy Thanks for pointing it out.

**Comment by suhanipaliwal** [comment]
I have started working on this issue. Could you please add a label of appropriate level like level 1, 2 or 3 for Gssoc'24.

**Comment by govind-kumarr** [comment]
@suhanipaliwal  Sure
