### ISSUE TITLE
Train AI page design

### ISSUE THREAD

**Issue by govind-kumarr** [govind-kumarr/simple_rag_dashboard#48]
I am planning to add a Train AI page where you can add basic instructions for the chatbot which will be considered at the time of answering queries. 

The first step is to create a design for this. There should be an input box and a list of instructions that will be fetched from the backend for each user. Upon adding a new instruction it should get added to the db. Currently, there is no collection for it. That is our next step and the last step would be to integrate APIs from the backend to the frontend.

![Screenshot (636)](https://github.com/govind-kumarr/simple_rag_dashboard/assets/106414173/effc36cc-1934-45f7-8d8c-52bfd9e89953)

**Comment by gk12** [comment]
I would like to work on this issue.

**Comment by Latish705** [comment]
@govind-kumarr I would like to work on this issue
