### ISSUE TITLE
user should be able to create new chat

### ISSUE THREAD

**Issue by govind-kumarr** [govind-kumarr/simple_rag_dashboard#9]
![Screenshot (628)](https://github.com/govind-kumarr/simple_rag_dashboard/assets/106414173/8914dca8-7584-4b6d-95e1-6d97605501d4)
There should be a button to create a new chat and User can switch between chats.

**Comment by ayan-joshi** [comment]
I would like to work on it @govind-kumarr

**Comment by Avanti12p** [comment]
i would like to work on it @govind-kumarr 
Also can you add level labels to the issue

**Comment by gk12** [comment]
I would like to work on this issue under GSSOC'24 .

**Comment by govind-kumarr** [comment]
HI, @Avanti12p @ayan-joshi  You guys can setup the project locally and find new issues. I will be happy to assign those to you. If you find any problem setting up the project locally let me know.
